# -------------------------------------------------------------------------------
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# -------------------------------------------------------------------------------
site_name: ACT3 RL Core - CoRL
site_author: ACT3
docs_dir: docs
site_description: "The following python project creates a python interface for training Deep RL - provides the base RL functionality and APIs to enable rapid ablation testing and setup"
repo_name: act3-rl/corl/
repo_url: https://git.act3-ace.com/act3-rl/corl/
site_url: https://git.act3-ace.com/
edit_uri: blob/main/docs/
site_dir: site

plugins:
  - search
  - macros
  - mkdocstrings
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py  # or any other name or path
  # - literate-nav:
  #   nav_file: reference/SUMMARY.md
  # - coverage
  - section-index
  - pdf-export:
      verbose: false
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: true
      # combined_output_path: pdf/document.pdf

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - navigation.tabs
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode


extra_css:
  - css/style.css
  - css/material.css
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@8.4.2/dist/mermaid.min.js

handlers:
  python:
    setup_commands:
    - import sys
    - sys.path.append("docs")
    selection:
      new_path_syntax: yes
    import:  # demonstration purpose in the docs
      - https://docs.python-requests.org/en/master/objects.inv

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://git.act3-ace.com
  - icon: fontawesome/brands/gitlab
    link: https://git.act3-ace.com/act3-rl/

nav:
  - "Introduction": index.md
  - "Concepts":
    - "Core Concepts": concepts.md
    - diverse-frame-rate.md
    - "Evaluation Framework":
      - "QuickStart Guide": evaluation_framework/quickstart_guide.md
      - "User Guide": evaluation_framework/user_guide.md
  - "Configuration": configuration.md
  - "Install": install.md
  - "License": license.md
  - "Credits": credits.md
  - "Contributing": contributing.md
  # - "Coverage Report": coverage.md
  - "Tasks":
    - "Docking 1D": tasks/docking_1d.md
