"agent": "corl.agents.base_agent.TrainableBaseAgent"
"config": {
    "parts": [
        {"part": "Controller_Gym"},
        {"part": "Sensor_State"},
    ],
    "episode_parameter_provider": !include baseline_epp.yml,
    "glues": [
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config": {
                "controller": "Controller_Gym",
            },
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config":{
                "sensor": "Sensor_State",
                "normalization": {
                  "enabled": False
                }
            }
        },
        {
            "functor": "corl.glues.common.projected_quantity.ProjectedQuantity",
            "config": {},
            "wrapped": {
                "quantity": {
                    "functor": "corl.glues.common.target_value.TargetValue",
                    "config": {
                        "target_value": 1.0,
                        "limit": {"minimum": -10.0, "maximum": 10.0},
                        "unit": "ft/s"
                    },
                },
                "angle1": {
                    "functor": "corl.glues.common.target_value.TargetValue",
                    "config": {
                        "target_value": 0.5,
                        "limit": {"minimum": -3.1416, "maximum": 3.1416},
                        "unit": "rad"
                    },
                },
            },
        },
    ],
    "dones": !include baseline_dones.yml,
    "rewards": !include baseline_rewards.yml,
}