# ---------------------------------------------------------------------------
#
#
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core.
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ---------------------------------------------------------------------------

"agent": "corl.agents.base_agent.TrainableBaseAgent"
"config": {
    "parts": [
        {"part": "Controller_Gym"},
        {"part": "Sensor_State"},
    ],
    "episode_parameter_provider": !include baseline_epp.yml,
    "glues": [
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config": {
                "controller": "Controller_Gym",
            },
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config":{
                "sensor": "Sensor_State",
                "normalization": {
                  "enabled": False
                }
            }
        },
        {
            "functor": "corl.glues.common.target_value_difference.TargetValueDifference",
            "wrapped": {
                "sensor": {
                    "functor": "corl.glues.common.observe_sensor.ObserveSensor",
                    "config":{
                        "sensor": "Sensor_State",
                        "normalization": {
                            "enabled": False
                        }
                    }
                },
            },
            "config":{
                "target_value": 0,
                "index": 0,
                "unit": N/A,
                "limit": {
                    "minimum": -5000,
                    "maximum": 5000,
                    "unit": N/A
                }
            },
        },
        {
            "name": "ArithmeticMultiGlue",
            "functor": "corl.glues.common.arithmetic_multi_glue.ArithmeticMultiGlue",
            "wrapped": [
                {
                    "name": "Target1",
                    "functor": "corl.glues.common.target_value.TargetValue",
                    "config":{
                        "target_value": 5,
                        "unit": "none",
                        "limit": {
                            "minimum": -10,
                            "maximum": 10,
                            "unit": "none"
                        }
                    },
                },
                {
                    "name": "Target1",
                    "functor": "corl.glues.common.target_value.TargetValue",
                    "config":{
                        "target_value": -5,
                        "unit": "none",
                        "limit": {
                            "minimum": -10,
                            "maximum": 10,
                            "unit": "none"
                        }
                    },
                },
            ],
            "config": {
                "mode": "sum",
                "limit": {
                    "minimum": -100,
                    "maximum": 100,
                    "unit": "none"
                }
            }
        }
    ],
    "dones": !include baseline_dones.yml,
    "rewards": [
        {
            "name": "OpenAIGymReward",
            "functor": "corl.rewards.openai_gym_reward.OpenAIGymReward",
            "config": {
            }
        },
        {
            "name": "OpenAIGymExtractorReward",
            "functor": "corl.rewards.exponential_decay_from_target_value.ExponentialDecayFromTargetValue",
            "config": {
                "observation": {
                    "fields": ["ObserveSensor_Sensor_StateDiff", "direct_observation_diff"]
                },
                "index": 0,
                "eps": 1, # THIS IS RADIANS
                "reward_scale": .000000000001,
                "is_closer": true,
                "closer_tolerance": 10,
            }
        }
    ],
}
