# ---------------------------------------------------------------------------
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core.
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ---------------------------------------------------------------------------
world:
  -
    name: Short Episodes
    metric: rate_of_runs_lt_5steps
    scope: evaluation
    thresholds:
      - type: warning
        condition:
          operator: ">"
          lhs: 0
