# ---------------------------------------------------------------------------
#
#
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core.
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ---------------------------------------------------------------------------

{
    "horizon": 180,
    "plugin_paths": ["corl.simulators.gymnasium"],
    "simulator":
        {
            "type": "GymnasiumSimulator",
            "config":
                {
                    "gymnasium_env": "CartPole-v1",
                    "seed": 1,
                    "wrappers": ["gymnasium.wrappers.TimeAwareObservation"],
                },
        },
    "episode_parameter_provider":
        {
            "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider",
        },
}
