# ---------------------------------------------------------------------------
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ---------------------------------------------------------------------------

####################################################################
# Override values used by the setup
####################################################################
auto_system_detect_class: corl.experiments.base_experiment.BaseAutoDetect
experiment_class: corl.experiments.rllib_experiment.RllibExperiment

config:
  # Example of PBT
  # hparam_search_class: corl.libraries.hparam_search_util.HparamSearchPPO_PBT
  # Example of ASHB
  # hparam_search_class: corl.libraries.hparam_search_util.HparamSearchPPO_AHBS
  policy_mapping:
    functor: corl.experiments.rllib_utils.policy_mapping_functions.SinglePolicy
    config:
      policy_id: "paddle0_ctrl"

  rllib_config_updates: &rllib_config_updates

  # No overrides for ray as there are no changes
  ray_config_updates: &ray_config_updates
    local_mode: False

  # Change the default path for saving out the data
  env_config_updates: &env_config_updates
    TrialName: Pong
    output_path: /tmp/aaco/act3

  # Change the default path for saving out the data
  tune_config_updates: &tune_config_updates
    local_dir: /tmp/aaco/ray_results/

  ####################################################################
  # Setup the actual keys used by the code
  # Note that items are patched from the update section
  ###################################################################
  rllib_configs:
    default: [!include ../rllib_config.yml, *rllib_config_updates]
    local: [!include ../rllib_config.yml,  *rllib_config_updates]

  ray_config: [!include ../ray_config.yml, *ray_config_updates]
  env_config: [!include ../environments/pong_env.yml, *env_config_updates]
  tune_config: [!include ../tune_config_ppo.yml, *tune_config_updates]
  extra_callbacks: [corl.environment.pickle_env_state.PongPickleEnvState, corl.environment.custom_env_metrics.CustomPongMetrics]

