# This config defines the environment for the training loop. This includes the Simulator entity, type of platform, path
# to the directory in which components (Sensors, Controllers, and Simulators) are registered with the PluginLibrary.


{
  "simulator": {
    "type": "Docking1dSimulator",
    "config": {
      "step_size": 1
    },
  },
  "platforms": "Docking1dSimulator_Platforms",
  "plugin_paths": ["corl"],
  "episode_parameter_provider": {
    "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider"
  },
  "simulator_reset_parameters": 
    {
      "platforms":
      {
        'blue0': 
          {
            'x': { 
              'type': 'corl.libraries.parameters.ConstantParameter',
              'config': 
                {'value': 10.0}
            },
            'xdot': { 
              'type': 'corl.libraries.parameters.ConstantParameter',
              'config':
                {'value': 0}
            }
          }
      }
    },

}
