# This config defines the environment for the training loop. This includes the Simulator entity, type of platform, path
# to the directory in which components (Sensors, Controllers, and Simulators) are registered with the PluginLibrary.


{
  "horizon": 1001,
  "simulator": {
    "type": "Docking1dSimulator",
    "config": {
      "step_size": 1
    },
  },
  "plugin_paths": ["corl"],
  "episode_parameter_provider": {
    "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider"
  },
  "simulator_reset_parameters":
    {
      "platforms":
      {
        'blue0':
          {
            'x': {
                        "type": "corl.libraries.parameters.UniformParameter",
                        "config": {
                            "units": "meter",
                            "low": -50,
                            "high": 50
                        }
                    },
            'xdot': {
                    "type": "corl.libraries.parameters.UniformParameter",
                    "config": {
                        "units": "meter / second",
                        "low": -1,
                        "high": 1
                    }
                },
          }
      }
    },

}
