# ---------------------------------------------------------------------------
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core.
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ---------------------------------------------------------------------------
# connection:
#   type: corl.evaluation.launchers.rest_eval_connection.RestEvalConnection

evaluator:
  type: corl.evaluation.runners.inference.inference.Inference
  config:
    algorithm_runner:
      exit_on_end: True

experiment:
  !merge
    - !include ./base_pong_evaluate.yml
    - !include ./inference.yml

run_forever: False
