eval_config: /home/vgangal/workspace/corl/config/evaluation/launch/eval_1d_docking.yml
gen_metrics_config: /home/vgangal/workspace/corl/config/evaluation/launch/metrics_gen_1d_docking.yml
visualize_config: /home/vgangal/workspace/corl/config/evaluation/launch/visualize_1d_docking.yml
storage_config: config/evaluation/launch/storage_acedt_1d_docking.yml
