storage_utility:
  - class_path: act3_corl.storage_utils.EvalAcedtBottleStorage
    init_args:
      bottle_location: /home/vgangal/workspace/1d_docking_bottle
      agent_type: docking1d
      team: CORL_dev_team
      experiment_name: 1d_docking_dummy
      experiment_description: train a dummy docking agent
      extra_labels:
        checkpoint_type: dummy 

artifacts_location_config: 
  eval_data_location: /home/vgangal/workspace/eval_framework_out/corl/docking1d
  metrics_file_location: /home/vgangal/workspace/eval_framework_out/corl/docking1d/metrics.pkl
  agent_checkpoints: 
    blue0: /home/vgangal/workspace/ACT3-RLLIB-AGENTS/Docking-1D-EpisodeParameterProviderSavingTrainer_ACT3MultiAgentEnv_27a11_00000_0_num_gpus=0,num_workers=23,rollout_fragment_length_2022-05-12_15-49-49/checkpoint_002200/checkpoint-2200
  event_table_location: /home/vgangal/workspace/eval_framework_out/corl/docking1d/event_table.txt
  